title: Mapa de supervivencia del apocalipsis zombi
hero_image: images/banner.png
description: Crea y navega por un mapa GPS para ayudarte a sobrevivir al apocalipsis zombi
theme: green # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-09-01
steps: 
- title: Introducción
- title: ¿Qué necesitarás?
- title: Crea una página web
- title: Obtenga una clave de API de Google Maps
- title: Mostrar el mapa
- title: Coloca un marcador
- title: Marque donde hace clic
- title: Elige tu icono
- title: Registre sus ubicaciones
- title: "Desafío: prepárate para los zombis"
